import Foundation
import SwiftUI

struct Offer: Identifiable, Codable {
    var id = UUID().uuidString //auto generated by my db & then turned into a String
    var title: String
    var typeOfOffer: String
    var estimatedTime: Float
    var numSessions: Int
    var datePosted: Date
    var materialsNeeded: String
    var description: String
    var locationPreferences: String //maybe make this a dict like this
    //[onlineOnly: bool, onlineOk: bool, onlinePreferred: bool, inPersonOnly: bool, inPersonOk: bool, inPersonPreferred: bool]
    //just make this into a dict stored in locationPreferences
    var onlineOnly: Bool
    var username: String
    var photo: String
    var comments: [String]
    var saved: [String]
}
