import Foundation
import SwiftUI

struct Offer: Identifiable, Codable {
    var id = UUID().uuidString //auto generated by my db & then turned into a String
    var title: String
    var typeOfOffer: String
    var estimatedTime: Float
    var numSessions: Int
    var datePosted: Date
    var materialsNeeded: String
    var description: String
    var locationPreferences: String //maybe make this a dict like this
    //[onlineOnly: bool, onlineOk: bool, onlinePreferred: bool, inPersonOnly: bool, inPersonOk: bool, inPersonPreferred: bool]
    //just make this into a dict stored in locationPreferences
    var onlineOnly: Bool
    var username: String
    var photo: String
    
}

//let offerTestData = [
//    Offer(id: "123", title: "Learn 2 Felt", typeOfOffer: "fiber craft", estimatedTime: 1.5, numSessions: 3, datePosted: Date.now, materialsNeeded: "felting wool, felting needle, dense sponge", description: "felting 4 beginners ~~ let me teach you how to felt a little country mouse", locationPreferences: "online or in person", onlineOnly: false, username: "coolthem555"),
//    Offer(id: "124", title: "This Is The Title", typeOfOffer: "this is the type of offer", estimatedTime: 5.3, numSessions: 2, datePosted: Date.now, materialsNeeded: "luck and good intentions", description: "beep bop this is my description", locationPreferences: "just online please", onlineOnly: true, username: "coffeeluvr123")
//]
